### ISSUE TITLE
exams2moodle fails on Windows writing UTF8 with Spanish characters 

### ISSUE THREAD

**Issue by noeliarico** [mbojan/exams#2]
The function perfectly works on Mac. Nevertheless, on Windows it fails to write the vowels with accents and thus it crushes when it is imported to Moodle.

According to https://tomizonor.wordpress.com/2013/04/17/file-utf8-windows/ it is because Windows has a different character set than Linux and Mac. 

I think that the problem may be that in the function the encoding parameter goes through an if structure and thus the concrete Windows character set cannot be pass to the writeLines function. 

Could you take a look at it, please?

Regards,
Noelia

**Comment by mbojan** [comment]
@noeliarico this is a fork of https://r-forge.r-project.org/projects/exams that I created for my own experiments. You should contact the original author and maintainer of `exams` via R-Forge or email.
